[Erro OpenAI: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BDF1FB6E40>: Failed to resolve 'api.openai.com' ([Errno 11001] getaddrinfo failed)"))]


[Erro OpenAI: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BDF23862A0>: Failed to resolve 'api.openai.com' ([Errno 11001] getaddrinfo failed)"))]


[Erro OpenAI: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BDF28AC7A0>: Failed to resolve 'api.openai.com' ([Errno 11001] getaddrinfo failed)"))]


[Erro OpenAI: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BDF24F8410>: Failed to resolve 'api.openai.com' ([Errno 11001] getaddrinfo failed)"))]


[Erro OpenAI: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BDF24FA720>: Failed to resolve 'api.openai.com' ([Errno 11001] getaddrinfo failed)"))]


[Erro OpenAI: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002BDF28AFD10>: Failed to resolve 'api.openai.com' ([Errno 11001] getaddrinfo failed)"))]